name: Generate AGI Blog Post

on:
  schedule:
    - cron: '11 13 * * *'  # 11:11 PM AEST = 13:11 UTC
  workflow_dispatch:

jobs:
  ghost-writer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install openai requests beautifulsoup4 python-dotenv pyyaml

    - name: Run ghost writer
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python ghost/ghost_writer.py

    - name: Improve Pong Game
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python ghost/pong_improver.py

    - name: Commit changes
      run: |
        git config --global user.name 'Lester Knight Chaykin'
        git config --global user.email 'lester@4511932.com'
        git add _posts/*.md
        git add assets/img/posts/*.jpg
        git add _data/images.yml
        git add assets/js/pong.js
        git commit -m "Automated AGI blog post" || echo "No changes to commit"
        git push
