name: Improve Pong Game

on:
  schedule:
    - cron: '11 13 * * *'  # 11:11 PM AEST = 13:11 UTC
  workflow_dispatch:

jobs:
  improve-pong:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install openai pyyaml

    - name: Run Pong Improver
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python ghost/pong_improver.py

    - name: Commit changes to pong.js
      run: |
        git config --global user.name 'Lester Knight Chaykin'
        git config --global user.email 'lester@4511932.com'
        git add assets/js/pong.js
        git add assets/css/pong.css
        git add _layouts/game.html
        git add _data/pong_history.yml
        git commit -m "Automated Pong game improvement" || echo "No changes to commit"
        git push
